download_url: https://galaxy.ansible.com/download/community-windows-2.0.0.tar.gz
format_version: 1.0.0
name: windows
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.0.0
version_url: https://galaxy.ansible.com/api/v2/collections/community/windows/versions/2.0.0/
