---

- name: Deploy de aplicação ASP.NET para IIS
  hosts: windows
  gather_facts: true
  tasks:
    
    - name: Parar o pool da aplicação - Ansiblewebpool
      ansible.windows.win_iis_webapppool:
        name: Ansiblewebpool
        state: stopped
    - name: Cópia dos arquivos para a pasta do Site
      ansible.windows.win_copy:
        src: C:\aplicativos\AspnetApp\wwwroot  
        dest: C:\inetpub\wwwroot\AWXAspnetApp
        remote_src: yes
    - name: Iniciar o Pool da aplicação
      ansible.windows.win_iis_webapppool:
        name: Ansiblewebpool
        state: started  
    - name: Configuração do Site no IIS 
      ansible.windows.win_iis_website: 
        name: AWXProject
        state: started
        port: 80
        ip: '*'
        hostname: awxansible.local
        application_pool: Ansiblewebpool 
        physical_path: C:\inetpub\wwwroot\AWXAspnetApp 
